# Generated by Django 5.2.6 on 2025-12-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_product_specifications_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chip_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chip xử lý (ví dụ: M1, M2 Pro)'),
        ),
    ]
