# Generated by Django 5.2.6 on 2025-12-15 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Danh mục',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('specifications', models.TextField(blank=True, verbose_name='Thông số kỹ thuật')),
                ('is_new', models.BooleanField(default=False, verbose_name='Sản phẩm mới')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Bán chạy nhất')),
                ('warranty_months', models.IntegerField(default=12, verbose_name='Bảo hành (tháng)')),
                ('shipping_info', models.CharField(default='Miễn phí toàn quốc', max_length=255, verbose_name='Thông tin vận chuyển')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(max_length=50, verbose_name='Dung lượng (GB/TB)')),
                ('color', models.CharField(max_length=50, verbose_name='Màu sắc')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá bán (VNĐ)')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='Phần trăm giảm giá (%)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='iphone_images/', verbose_name='Ảnh biến thể')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='home.product', verbose_name='Sản phẩm gốc')),
            ],
            options={
                'verbose_name_plural': 'Biến thể sản phẩm',
                'ordering': ['price'],
                'unique_together': {('product', 'storage', 'color')},
            },
        ),
    ]
