# Generated by Django 5.2.6 on 2025-12-15 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Thuộc tính (ví dụ: Màn hình, Chip xử lý)')),
                ('value', models.CharField(max_length=255, verbose_name='Giá trị (ví dụ: OLED 6.5 inches, Apple A13 Bionic)')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='home.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Thông số kỹ thuật',
                'verbose_name_plural': 'Thông số kỹ thuật',
                'ordering': ['product', 'order'],
            },
        ),
    ]
