# Generated by Django 5.2.6 on 2025-12-16 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_chip_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('summary', models.TextField(verbose_name='Tóm tắt nội dung')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đăng')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nguồn tin')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Hình ảnh')),
                ('external_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Đường dẫn Đọc thêm')),
                ('is_store_info', models.BooleanField(default=False, verbose_name='Là thông tin cửa hàng')),
            ],
            options={
                'verbose_name': 'Tin tức',
                'verbose_name_plural': 'Tin tức & Cập nhật',
                'ordering': ['-published_date'],
            },
        ),
    ]
